version: '3.7'
services:
  app:
    container_name: gg-api-app
    restart: always
    build: .
    environment:
         - spring.datasource.url=jdbc:postgresql://postgres:5432/invillia_challenger
    volumes:
      - .:/app/gg-api
      - ~/.m2:/root/.m2
   
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks: 
      - backend
    command: mvn spring-boot:run

  postgres:
    container_name: gg-api-db
    restart: always
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
 
         - POSTGRES_PASSWORD=post
         - POSTGRES_USER=postgres
         - POSTGRES_DB=invillia_challenger
    ports:
      - 5432:5432
    networks: 
      - backend
    restart: unless-stopped


  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "juniorcreti@gmail.com"
    
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - backend



networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
    driver: local
    name: postgres-data